---
apiVersion: v1
kind: Namespace
metadata:
  name: restricted
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.26
---
apiVersion: v1
kind: Namespace
metadata:
  name: privileged
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.26
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: restricted
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: web
          image: nginxinc/nginx-unprivileged:1.16.1-alpine
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: v1
kind: Pod
metadata:
  name: podman
  namespace: privileged
spec:
  containers:
    - name: priv
      image: quay.io/podman/stable
      args:
        - sleep
        - "1000000"
      securityContext:
        privileged: true
